ShaperTools/configuration-ci-general

sources/index.yml

Changed commit message check for merge method

fix: Change commit message check for merge method

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.1.0

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.1.1

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.1.2

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.1.3

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.1.4

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.3.0

---

sources/index.yml

Set the resource call for node executor.

fix: Increase the resource class

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.3.6

---

sources/index.yml

Allow the executor to be passed into the job

fix: Expose the executor to jobs

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.3.7

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.3.8

---

sources/index.yml

Set npm install timeout to 20 mins

fix: Sets timeout to 20 mins

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.3.9

---

sources/index.yml

Add `region` parameter to `configure-aws-profile` command

Add region parameter

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.4.0

---

sources/index.yml

Remove braces in `region` parameter

Remove braces in region parameter

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.4.1

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.0

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.1

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.2

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.3

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.6.0

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.4

---

sources/index.yml

Install `aws-cli` in cleanup jobs

Install AWS CLI in cleanup jobs

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.5

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.6

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.7

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.5.10

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.7.0

---

sources/index.yml

For [https://shaper.atlassian.net/browse/WREQ-1094](https://shaper.atlassian.net/browse/WREQ-1094)

fix: Cleanup PR and commit deployments older than 14 days

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.7.1

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.7.2

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.7.3

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.7.4

---

CHANGELOG.md
package-lock.json
package.json

New Release: v0.7.5
